from __future__ import annotations

import csv
import json
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo


SHANGHAI = ZoneInfo("Asia/Shanghai")


def normalize_topic(topic: str) -> str:
    normalized = topic.strip()
    return normalized or "未分类"


def split_pictures(value: str) -> list[str]:
    return [item.strip() for item in value.splitlines() if item.strip()]


def parse_datetime(iso_string: str) -> datetime:
    return datetime.fromisoformat(iso_string.replace("Z", "+00:00")).astimezone(SHANGHAI)


def format_date_label(iso_string: str) -> str:
    dt = parse_datetime(iso_string)
    return f"{dt.year}年{dt.month}月{dt.day}日"


def make_excerpt(text: str) -> str:
    compact = " ".join(text.split())
    return compact[:120]


def build_post(row: dict[str, str]) -> dict[str, object]:
    content = row["content"].strip()
    repost_author = row["repost_author"].strip()
    repost_content = row["repost_content"].strip()
    pictures = split_pictures(row["picture_urls"])
    created_at = row["created_at"].strip()
    dt = parse_datetime(created_at)

    return {
        "id": row["id"].strip(),
        "createdAt": created_at,
        "dateLabel": format_date_label(created_at),
        "year": dt.year,
        "author": row["author"].strip(),
        "topic": normalize_topic(row["topic"]),
        "link": row["link"].strip(),
        "content": content,
        "excerpt": make_excerpt(content or repost_content),
        "pictures": pictures,
        "pictureCount": len(pictures),
        "repost": (
            {
                "author": repost_author,
                "content": repost_content,
            }
            if repost_author or repost_content
            else None
        ),
    }


def to_ts_module(posts: list[dict[str, object]], source_path: str) -> str:
    header = "\n".join(
        [
            "// This file is generated by scripts/import-jike-csv.py",
            f"// Source: {source_path}",
            "export const jikePosts = ",
        ]
    )
    return f"{header}{json.dumps(posts, ensure_ascii=False, indent=2)};\n"


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/import-jike-csv.py <input.csv> [output.ts]", file=sys.stderr)
        raise SystemExit(1)

    input_path = Path(sys.argv[1]).expanduser().resolve()
    output_path = (
        Path(sys.argv[2]).expanduser().resolve()
        if len(sys.argv) > 2
        else Path.cwd() / "src/data/jike-posts.generated.ts"
    )

    with input_path.open("r", encoding="utf-8-sig", newline="") as file:
        rows = list(csv.DictReader(file))

    posts = sorted((build_post(row) for row in rows), key=lambda post: post["createdAt"], reverse=True)
    output_path.write_text(to_ts_module(posts, str(input_path)), encoding="utf-8")
    print(f"Imported {len(posts)} Jike posts to {output_path}")


if __name__ == "__main__":
    main()
